name: Renovate

on:
  schedule:
    # Run every Monday at 6 AM UTC
    - cron: "0 6 * * 1"
  workflow_dispatch:
  # Trigger when dependency files change
  push:
    paths:
      - "pyproject.toml"
      - "Dockerfile"
      - ".github/workflows/*.yml"
      - ".github/renovate.json"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.2
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: info
          RENOVATE_AUTODISCOVER: false
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
